name: Docker-CI

on:
  push:
    branches:
      - 'main'

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:amd64

  arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: arm64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:arm64

  amd64-274:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            READER_VERSION=2.7.4
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:2.7.4-amd64

  arm64-274:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: arm64.Dockerfile
          platforms: linux/arm64
          build-args: |
            READER_VERSION=2.7.4
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:2.7.4-arm64

  tag-latest:
    needs: [amd64, arm64]
    name: version tag latest
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: create latest tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:arm64

  tag-274:
    needs: [amd64-274, arm64-274]
    name: version tag 274
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: create latest tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:2.7.4 \
            ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:2.7.4-amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/kindle-reader-web-cli:2.7.4-arm64
